enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
custom_logo:
  user/themes/quark/images/logo/Logo_tuermli-braeu.png:
    name: Logo_tuermli-braeu.png
    type: image/png
    size: 22098
    path: user/themes/quark/images/logo/Logo_tuermli-braeu.png
custom_logo_mobile: {  }
